version: "3.9"

services:
  muralink-image-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: muralink-image-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
